//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bandeira.GerenciadorCampeonatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campeonato
    {
        public Campeonato()
        {
            this.Rodadas = new HashSet<Rodada>();
            this.Pontuacoes = new HashSet<Pontuacao>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Rodada> Rodadas { get; set; }
        public virtual ICollection<Pontuacao> Pontuacoes { get; set; }
    }
}
