//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bandeira.GerenciadorCampeonatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competidor
    {
        public int Id { get; set; }
        public int PartidaId { get; set; }
    
        public virtual Partida Partida { get; set; }
        public virtual Jogador Jogador { get; set; }
        public virtual Resultado Resultado { get; set; }
    }
}
