//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bandeira.GerenciadorCampeonatos.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GerenciadorCampeonatosContainer : DbContext
    {
        public GerenciadorCampeonatosContainer()
            : base("name=GerenciadorCampeonatosContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public IDbSet<Campeonato> Campeonatos { get; set; }
        public IDbSet<Rodada> Rodadas { get; set; }
        public IDbSet<Partida> Partidas { get; set; }
        public IDbSet<Competidor> Competidores { get; set; }
        public IDbSet<Jogador> Jogadores { get; set; }
        public IDbSet<Pontuacao> Pontuacoes { get; set; }
        public IDbSet<ResultadoPartida> Resultados { get; set; }
        public IDbSet<Local> Locais { get; set; }
        public IDbSet<JogadorCampeonato> JogadorCampeonatos { get; set; }
    }
}
