//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bandeira.GerenciadorCampeonatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pontuacao
    {
        public Pontuacao()
        {
            this.Resultados = new HashSet<ResultadoPartida>();
        }
    
        public int Id { get; set; }
        public int CampeonatoId { get; set; }
        public int Colocacao { get; set; }
        public int Pontos { get; set; }
        public System.DateTime DtCadastro { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Campeonato Campeonato { get; set; }
        public virtual ICollection<ResultadoPartida> Resultados { get; set; }
    }
}
